name: hover
description: A helper and widget library for implementing navigation, theme management, and responsive layouts for Flutter apps.
version: 0.4.1
homepage: https://github.com/ernpao/hover

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter    
  provider: ^5.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

