name: hover
description: A helper and widget library for navigation, theme switching, responsive design, and more that aims to reduce boilerplate code for Flutter app development
version: 0.2.0
homepage: https://github.com/ernpao/hover

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter    
  provider: ^5.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

