name: hover
description: A helper and widget library for implementing navigation, theme management, and responsive layouts for Flutter apps.
version: 0.4.1
homepage: https://github.com/ernpao/hover

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter    
  provider: ^6.0.1
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

